# Generated by Django 5.1.4 on 2024-12-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('equipoLocal', models.CharField(max_length=100)),
                ('equipoVisitante', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
            ],
        ),
    ]
